-- Create enum types
CREATE TYPE user_status AS ENUM ('ACTIVE', 'CREDENTIALS_EXPIRED', 'LOCKED', 'EXPIRED', 'INACTIVE', 'SUSPENDED', 'DELETED');
CREATE TYPE user_role AS ENUM ('ADMIN', 'MODERATOR', 'USER', 'GUEST');
CREATE TYPE chat_status AS ENUM ('ACTIVE', 'ARCHIVED', 'DELETED');
CREATE TYPE message_sender AS ENUM ('USER', 'MODEL', 'SYSTEM');

